name: Integración continua para Frontend en prueba de Walmart

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm ci

      - name: Dependencias
        run: npm install

      - name: Dependencias
        run: npm install

      #- name: Testing
      #  run: npm test

      - name: Build, Push y Deploy a Heroku
        id: heroku
        uses: jctaveras/heroku-deploy@v2.0.0
        with:
          email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
          api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
          app_name: ${{ secrets.HEROKU_APP_NAME }} # you aplication name
          dockerfile_path: "." # set the path to the folder wher the Dokerfile is located
          options: "-t" # Docker Build Options

