name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name:   Checkout
    - uses: actions/checkout@v2

    - name: Dependencias
      run: npm install

    #- name: Testing
    #  run: npm test
    
    - name: Start
      run: npm run-script build

    - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
      id: heroku
      uses: jctaveras/heroku-deploy@v2.0.0  # use the latest version of the action
      with:
        email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
        api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
        app_name: ${{ secrets.HEROKU_APP_NAME }} # you aplication name
        dockerfile_path: '' # set the path to the folder wher the Dokerfile is located
        options: '' # Docker Build Options

